# Generated by Django 4.0 on 2021-12-07 22:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Raridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('nome_ingles', models.CharField(max_length=1000)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards.cor')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards.edicao')),
                ('raridade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards.raridade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards.tipo')),
            ],
        ),
    ]
